/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as MatRouteImport } from './routes/mat'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ForTeachersRouteImport } from './routes/for-teachers'
import { Route as ForStudentsRouteImport } from './routes/for-students'
import { Route as ForSchoolsRouteImport } from './routes/for-schools'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesQuizArenaRouteImport } from './routes/games.quiz-arena'
import { Route as GamesMemoryMatchRouteImport } from './routes/games.memory-match'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedSchoolAdminRouteImport } from './routes/_authenticated/school-admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLearnSlugRouteImport } from './routes/_authenticated/learn.$slug'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const MatRoute = MatRouteImport.update({
  id: '/mat',
  path: '/mat',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ForTeachersRoute = ForTeachersRouteImport.update({
  id: '/for-teachers',
  path: '/for-teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForStudentsRoute = ForStudentsRouteImport.update({
  id: '/for-students',
  path: '/for-students',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSchoolsRoute = ForSchoolsRouteImport.update({
  id: '/for-schools',
  path: '/for-schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesQuizArenaRoute = GamesQuizArenaRouteImport.update({
  id: '/quiz-arena',
  path: '/quiz-arena',
  getParentRoute: () => GamesRoute,
} as any)
const GamesMemoryMatchRoute = GamesMemoryMatchRouteImport.update({
  id: '/memory-match',
  path: '/memory-match',
  getParentRoute: () => GamesRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolAdminRoute =
  AuthenticatedSchoolAdminRouteImport.update({
    id: '/school-admin',
    path: '/school-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnSlugRoute = AuthenticatedLearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/experiments': typeof ExperimentsRoute
  '/for-schools': typeof ForSchoolsRoute
  '/for-students': typeof ForStudentsRoute
  '/for-teachers': typeof ForTeachersRoute
  '/games': typeof GamesRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/mat': typeof MatRoute
  '/puzzles': typeof PuzzlesRoute
  '/vocabulary': typeof VocabularyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/school-admin': typeof AuthenticatedSchoolAdminRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/games/memory-match': typeof GamesMemoryMatchRoute
  '/games/quiz-arena': typeof GamesQuizArenaRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/experiments': typeof ExperimentsRoute
  '/for-schools': typeof ForSchoolsRoute
  '/for-students': typeof ForStudentsRoute
  '/for-teachers': typeof ForTeachersRoute
  '/games': typeof GamesRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/mat': typeof MatRoute
  '/puzzles': typeof PuzzlesRoute
  '/vocabulary': typeof VocabularyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/school-admin': typeof AuthenticatedSchoolAdminRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/games/memory-match': typeof GamesMemoryMatchRoute
  '/games/quiz-arena': typeof GamesQuizArenaRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/experiments': typeof ExperimentsRoute
  '/for-schools': typeof ForSchoolsRoute
  '/for-students': typeof ForStudentsRoute
  '/for-teachers': typeof ForTeachersRoute
  '/games': typeof GamesRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/mat': typeof MatRoute
  '/puzzles': typeof PuzzlesRoute
  '/vocabulary': typeof VocabularyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/school-admin': typeof AuthenticatedSchoolAdminRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/games/memory-match': typeof GamesMemoryMatchRoute
  '/games/quiz-arena': typeof GamesQuizArenaRoute
  '/_authenticated/learn/$slug': typeof AuthenticatedLearnSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/courses'
    | '/experiments'
    | '/for-schools'
    | '/for-students'
    | '/for-teachers'
    | '/games'
    | '/leaderboard'
    | '/mat'
    | '/puzzles'
    | '/vocabulary'
    | '/dashboard'
    | '/school-admin'
    | '/teacher'
    | '/courses/$slug'
    | '/games/memory-match'
    | '/games/quiz-arena'
    | '/learn/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/courses'
    | '/experiments'
    | '/for-schools'
    | '/for-students'
    | '/for-teachers'
    | '/games'
    | '/leaderboard'
    | '/mat'
    | '/puzzles'
    | '/vocabulary'
    | '/dashboard'
    | '/school-admin'
    | '/teacher'
    | '/courses/$slug'
    | '/games/memory-match'
    | '/games/quiz-arena'
    | '/learn/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/courses'
    | '/experiments'
    | '/for-schools'
    | '/for-students'
    | '/for-teachers'
    | '/games'
    | '/leaderboard'
    | '/mat'
    | '/puzzles'
    | '/vocabulary'
    | '/_authenticated/dashboard'
    | '/_authenticated/school-admin'
    | '/_authenticated/teacher'
    | '/courses/$slug'
    | '/games/memory-match'
    | '/games/quiz-arena'
    | '/_authenticated/learn/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  ExperimentsRoute: typeof ExperimentsRoute
  ForSchoolsRoute: typeof ForSchoolsRoute
  ForStudentsRoute: typeof ForStudentsRoute
  ForTeachersRoute: typeof ForTeachersRoute
  GamesRoute: typeof GamesRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  MatRoute: typeof MatRoute
  PuzzlesRoute: typeof PuzzlesRoute
  VocabularyRoute: typeof VocabularyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mat': {
      id: '/mat'
      path: '/mat'
      fullPath: '/mat'
      preLoaderRoute: typeof MatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-teachers': {
      id: '/for-teachers'
      path: '/for-teachers'
      fullPath: '/for-teachers'
      preLoaderRoute: typeof ForTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-students': {
      id: '/for-students'
      path: '/for-students'
      fullPath: '/for-students'
      preLoaderRoute: typeof ForStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-schools': {
      id: '/for-schools'
      path: '/for-schools'
      fullPath: '/for-schools'
      preLoaderRoute: typeof ForSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/quiz-arena': {
      id: '/games/quiz-arena'
      path: '/quiz-arena'
      fullPath: '/games/quiz-arena'
      preLoaderRoute: typeof GamesQuizArenaRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/memory-match': {
      id: '/games/memory-match'
      path: '/memory-match'
      fullPath: '/games/memory-match'
      preLoaderRoute: typeof GamesMemoryMatchRouteImport
      parentRoute: typeof GamesRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school-admin': {
      id: '/_authenticated/school-admin'
      path: '/school-admin'
      fullPath: '/school-admin'
      preLoaderRoute: typeof AuthenticatedSchoolAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$slug': {
      id: '/_authenticated/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof AuthenticatedLearnSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSchoolAdminRoute: typeof AuthenticatedSchoolAdminRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRoute
  AuthenticatedLearnSlugRoute: typeof AuthenticatedLearnSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSchoolAdminRoute: AuthenticatedSchoolAdminRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRoute,
  AuthenticatedLearnSlugRoute: AuthenticatedLearnSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface GamesRouteChildren {
  GamesMemoryMatchRoute: typeof GamesMemoryMatchRoute
  GamesQuizArenaRoute: typeof GamesQuizArenaRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesMemoryMatchRoute: GamesMemoryMatchRoute,
  GamesQuizArenaRoute: GamesQuizArenaRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CoursesRoute: CoursesRouteWithChildren,
  ExperimentsRoute: ExperimentsRoute,
  ForSchoolsRoute: ForSchoolsRoute,
  ForStudentsRoute: ForStudentsRoute,
  ForTeachersRoute: ForTeachersRoute,
  GamesRoute: GamesRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  MatRoute: MatRoute,
  PuzzlesRoute: PuzzlesRoute,
  VocabularyRoute: VocabularyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
